"""Move rental_num from book model to user model

Revision ID: ac4be06a2e46
Revises: 0d919238843a
Create Date: 2023-08-30 19:26:01.587010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac4be06a2e46'
down_revision = '0d919238843a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('rental_val')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rental_num')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_val', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
