"""change rent table

Revision ID: f700953426b8
Revises: 44c0113636eb
Create Date: 2023-08-11 01:11:07.836874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f700953426b8'
down_revision = '44c0113636eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('returned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('due_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
